# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\laragon\www\boxqt\Testing\Bluetooth Scanner Example\service.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ServiceDiscovery(object):
    def setupUi(self, ServiceDiscovery):
        ServiceDiscovery.setObjectName("ServiceDiscovery")
        ServiceDiscovery.resize(539, 486)
        self.verticalLayout = QtWidgets.QVBoxLayout(ServiceDiscovery)
        self.verticalLayout.setObjectName("verticalLayout")
        self.list = QtWidgets.QListWidget(ServiceDiscovery)
        self.list.setObjectName("list")
        self.verticalLayout.addWidget(self.list)
        self.status = QtWidgets.QLabel(ServiceDiscovery)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.buttonBox = QtWidgets.QDialogButtonBox(ServiceDiscovery)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ServiceDiscovery)
        self.buttonBox.accepted.connect(ServiceDiscovery.accept) # type: ignore
        self.buttonBox.rejected.connect(ServiceDiscovery.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ServiceDiscovery)

    def retranslateUi(self, ServiceDiscovery):
        _translate = QtCore.QCoreApplication.translate
        ServiceDiscovery.setWindowTitle(_translate("ServiceDiscovery", "Available Services"))
        self.status.setText(_translate("ServiceDiscovery", "Querying..."))
