# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about_this_app_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutThisAppDialog(object):
    def setupUi(self, AboutThisAppDialog):
        AboutThisAppDialog.setObjectName("AboutThisAppDialog")
        AboutThisAppDialog.setWindowModality(QtCore.Qt.WindowModal)
        AboutThisAppDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(AboutThisAppDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(AboutThisAppDialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(AboutThisAppDialog)
        QtCore.QMetaObject.connectSlotsByName(AboutThisAppDialog)

    def retranslateUi(self, AboutThisAppDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutThisAppDialog.setWindowTitle(_translate("AboutThisAppDialog", "About this app"))
        self.label.setText(_translate("AboutThisAppDialog", "TextLabel"))
